# Generated by Django 6.0.7 on 2026-08-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
