# Generated by Django 6.0.7 on 2026-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вага (г)'),
        ),
    ]
