# Generated by Django 6.0.7 on 2026-08-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
