# Generated by Django 6.0.7 on 2026-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_dish_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса доставки'),
        ),
    ]
