# Generated by Django 6.0.7 on 2026-09-13 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_profile_delivery_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адреса доставки')),
                ('delivery_method', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Спосіб отримання')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сума страв')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Доставка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Разом')),
                ('payment_method', models.CharField(default='При отриманні', max_length=50, verbose_name='Оплата')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В роботі'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=64, verbose_name='Страва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сума')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order')),
            ],
        ),
    ]
